---
# Apply latest style guide and new cops
AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable

# ignore block length in test code only
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - app/application/controllers/**/*.rb
    - Rakefile

Style/MixinUsage:
  Enabled: true
  Exclude:
    - load_all.rb

Style/OpenStructUse:
  Enabled: false