---

development:
  DB_FILENAME: db/local/dev.db
  API_KEY: <RapidAPI_API_KEY>
  SESSION_SECRET: <SESSION_SECRET>
  API_HOST: <API_HOST_URL>

test:
  DB_FILENAME: db/local/test.db
  API_KEY: <RapidAPI_API_KEY>
  SESSION_SECRET: <SESSION_SECRET>
  API_HOST: <API_HOST_URL>

production:
  API_HOST: http://url.to.api
  SESSION_SECRET: <SESSION_SECRET>